<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class BarangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // \App\Models\Barang::factory()->count(50)->create();
        \App\Models\Barang::factory()->createMany([
            [
                'kode' => 'PR001',
                'nama' => 'Sunco 2 Liter',
                'id_jenis_barang' => 7,
                'harga' => 20000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR002',
                'nama' => 'Bimoli 1 Liter',
                'id_jenis_barang' => 7,
                'harga' => 15000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR003',
                'nama' => 'Bimoli 2 Liter',
                'id_jenis_barang' => 7,
                'harga' => 25000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR004',
                'nama' => 'Sania 1 Liter',
                'id_jenis_barang' => 7,
                'harga' => 13000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR005',
                'nama' => 'Sania 2 Liter',
                'id_jenis_barang' => 7,
                'harga' => 30000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR006',
                'nama' => 'Filma 1 Liter',
                'id_jenis_barang' => 7,
                'harga' => 15000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR007',
                'nama' => 'Filma 2 Liter',
                'id_jenis_barang' => 7,
                'harga' => 25000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR008',
                'nama' => 'Tropical 1 liter',
                'id_jenis_barang' => 7,
                'harga' => 15000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR009',
                'nama' => 'Tropical 2 Liter',
                'id_jenis_barang' => 7,
                'harga' => 30000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR010',
                'nama' => 'Fortune 1 Liter',
                'id_jenis_barang' => 7,
                'harga' => 15000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR011',
                'nama' => 'Fortune 2 Liter',
                'id_jenis_barang' => 7,
                'harga' => 30000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR012',
                'nama' => 'Kunci Mas 1 Liter',
                'id_jenis_barang' => 7,
                'harga' => 19000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR013',
                'nama' => 'Kunci Mas 2 Liter',
                'id_jenis_barang' => 7,
                'harga' => 25000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR014',
                'nama' => 'Bimoli 5 Liter',
                'id_jenis_barang' => 7,
                'harga' => 100000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR015',
                'nama' => 'Head & Shoulder 170 ml',
                'id_jenis_barang' => 8,
                'harga' => 26000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR016',
                'nama' => 'Pantene Conditioner 290 ml',
                'id_jenis_barang' => 8,
                'harga' => 40000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR017',
                'nama' => 'Pantene Shampoo Gold Series 125ml Smooth Sleek',
                'id_jenis_barang' => 8,
                'harga' => 19000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR018',
                'nama' => 'REJOICE Shampoo Rich 150 ML',
                'id_jenis_barang' => 8,
                'harga' => 15000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR019',
                'nama' => 'Dove Daily Shine Shampoo',
                'id_jenis_barang' => 8,
                'harga' => 15000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR020',
                'nama' => 'Shampo Lifebuoy Botol 340 ml',
                'id_jenis_barang' => 8,
                'harga' => 18000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR021',
                'nama' => 'Lifebuoy Shampoo Anti Hair Fall [680 mL]',
                'id_jenis_barang' => 8,
                'harga' => 40000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR022',
                'nama' => 'Sunsilk Hijab Refresh & Anti Dandruff [170 ml]',
                'id_jenis_barang' => 8,
                'harga' => 15000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR023',
                'nama' => 'Mie Sedaap Goreng 90 gr',
                'id_jenis_barang' => 1,
                'harga' => 1500,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR024',
                'nama' => 'Mie Sedaap R.Korean Spicy Soup 77 gr',
                'id_jenis_barang' => 1,
                'harga' => 1500,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR025',
                'nama' => 'Mie Sedaap R.Korean Spicy Chicken 87 gr',
                'id_jenis_barang' => 1,
                'harga' => 1500,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR026',
                'nama' => 'Mie Sedaap R.Kari Ayam 72 gr',
                'id_jenis_barang' => 1,
                'harga' => 1500,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR027',
                'nama' => 'Mie Sedaap R.Kari Special 85 gr',
                'id_jenis_barang' => 1,
                'harga' => 1500,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR028',
                'nama' => 'Anlene Actifit Cokelat Susu Bubuk Dewasa [250 g]',
                'id_jenis_barang' => 2,
                'harga' => 32000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR029',
                'nama' => 'DANCOW 3 Vanila Susu Box 400 g',
                'id_jenis_barang' => 2,
                'harga' => 45000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR030',
                'nama' => 'Susu UHT Ultra Milk Full Cream 1L',
                'id_jenis_barang' => 2,
                'harga' => 15000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR031',
                'nama' => 'oatside 200ml',
                'id_jenis_barang' => 2,
                'harga' => 5000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR032',
                'nama' => 'Greenfields UHT Milk Choco Malt [125 mL]',
                'id_jenis_barang' => 2,
                'harga' => 4000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR033',
                'nama' => 'PRENAGEN MOMMY UHT COKLAT 200 ML',
                'id_jenis_barang' => 2,
                'harga' => 6000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR034',
                'nama' => 'Ale-Ale Leci Cup 180 ml',
                'id_jenis_barang' => 2,
                'harga' => 1000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR035',
                'nama' => 'Ale-Ale Guava Cup 180 ml',
                'id_jenis_barang' => 2,
                'harga' => 1000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR036',
                'nama' => 'Ale-Ale Orange Cup 180 ml',
                'id_jenis_barang' => 2,
                'harga' => 1000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR037',
                'nama' => 'CITRA Sabun Mandi Batang Aloe Vera 70 g',
                'id_jenis_barang' => 8,
                'harga' => 1500,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR038',
                'nama' => 'Cussons Baby Hair & Body Wash Mild & Gentle - 400 ml',
                'id_jenis_barang' => 8,
                'harga' => 25000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR039',
                'nama' => 'Dettol bodywash 625 gr pump ',
                'id_jenis_barang' => 8,
                'harga' => 28000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR040',
                'nama' => 'Biore Body Foam Whitening Scrub Sabun Mandi Cair [100 mL]',
                'id_jenis_barang' => 8,
                'harga' => 7000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR041',
                'nama' => 'GIV Body Wash Sabun Mandi Cair Refill 900 ML Flower Glowing White GIV',
                'id_jenis_barang' => 8,
                'harga' => 18000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR042',
                'nama' => 'BETADINE Pomegranate Body Wash [400 mL]',
                'id_jenis_barang' => 8,
                'harga' => 45000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR043',
                'nama' => 'Mama Lemon Jeruk Nipis 800ml MULTICOLOR',
                'id_jenis_barang' => 8,
                'harga' => 10000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR044',
                'nama' => 'Sabun Lifebuoy Cair Btl 100 ml',
                'id_jenis_barang' => 8,
                'harga' => 10000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR045',
                'nama' => 'Sabun Lifebuoy Cair Ref 250 ml',
                'id_jenis_barang' => 8,
                'harga' => 10000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR046',
                'nama' => 'Lux Body Wash Soft Rose Sabun Cair [250 mL/ Refill]',
                'id_jenis_barang' => 8,
                'harga' => 12000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR047',
                'nama' => 'NUVO Family Protect Body Wash Cair Refill 900ml 900 ml',
                'id_jenis_barang' => 8,
                'harga' => 25000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR048',
                'nama' => 'Shinzui Skin Lightening Body Cleanser Kirei Sabun Mandi Cair [500 mL]',
                'id_jenis_barang' => 8,
                'harga' => 45000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR049',
                'nama' => 'NESTLE PURE LIFE Air Mineral Botol [1500 mL]',
                'id_jenis_barang' => 2,
                'harga' => 5000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR050',
                'nama' => 'Crystalline Air Mineral 600Ml',
                'id_jenis_barang' => 2,
                'harga' => 3300,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR051',
                'nama' => 'Cleo Eco Pack Drinking Water Air Mineral – 550 ml',
                'id_jenis_barang' => 2,
                'harga' => 2000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR052',
                'nama' => 'Vit Air Mineral Botol 550 mL',
                'id_jenis_barang' => 2,
                'harga' => 2000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR053',
                'nama' => 'Le Minerale Air Mineral [1500 mL/ Botol]',
                'id_jenis_barang' => 2,
                'harga' => 3500,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR054',
                'nama' => 'Aqua Air Mineral [600 mL]',
                'id_jenis_barang' => 2,
                'harga' => 3500,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR055',
                'nama' => 'ADES AIR MINERAL 600 ML',
                'id_jenis_barang' => 2,
                'harga' => 2500,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR056',
                'nama' => 'PRISTINE Air Mineral [600 mL/ Botol]',
                'id_jenis_barang' => 2,
                'harga' => 4000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR057',
                'nama' => 'Club 600 ml ',
                'id_jenis_barang' => 2,
                'harga' => 1000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR058',
                'nama' => 'Teh Botol Sosro 350 ml',
                'id_jenis_barang' => 2,
                'harga' => 4000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR059',
                'nama' => 'Fruit tea 350ml',
                'id_jenis_barang' => 2,
                'harga' => 4000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR060',
                'nama' => 'NU GREEN TEA HONEY 500 ML',
                'id_jenis_barang' => 2,
                'harga' => 4500,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR061',
                'nama' => 'Frestea Green Tea Honey Minuman Teh Hijau Rasa Madu [500 mL]',
                'id_jenis_barang' => 2,
                'harga' => 4000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR062',
                'nama' => 'Ichi Ocha Teh Melati 350ml ',
                'id_jenis_barang' => 2,
                'harga' => 3500,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR063',
                'nama' => 'Pulpy orange 300ml',
                'id_jenis_barang' => 2,
                'harga' => 3000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR064',
                'nama' => 'Mogu Mogu Leci 320ml ',
                'id_jenis_barang' => 2,
                'harga' => 7000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR065',
                'nama' => 'Mizone White Isotonic Lychee Lemon White Tea - 500 ml',
                'id_jenis_barang' => 2,
                'harga' => 7000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR066',
                'nama' => 'Ciptadent Pasta Gigi Maxi White 65 Gr',
                'id_jenis_barang' => 4,
                'harga' => 7000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR067',
                'nama' => 'CLOSE UP Pasta Gigi Green [65 gr]',
                'id_jenis_barang' => 4,
                'harga' => 7000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR068',
                'nama' => 'Pepsodent Pasta Gigi White 25 Gram',
                'id_jenis_barang' => 4,
                'harga' => 2000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR069',
                'nama' => 'Pepsodent 75 gr',
                'id_jenis_barang' => 4,
                'harga' => 3500,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR070',
                'nama' => 'Pepsodent 120 gr',
                'id_jenis_barang' => 4,
                'harga' => 7000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR071',
                'nama' => 'Pepsodent Pasta Gigi Whitening 190g',
                'id_jenis_barang' => 4,
                'harga' => 10000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR072',
                'nama' => 'Pepsodent Pasta Gigi Kids Strawberry - 50G',
                'id_jenis_barang' => 4,
                'harga' => 4000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR073',
                'nama' => 'Pepsodent Herbal 190 gr',
                'id_jenis_barang' => 4,
                'harga' => 13000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR074',
                'nama' => 'Taro net seaweed 65gr',
                'id_jenis_barang' => 1,
                'harga' => 5500,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR075',
                'nama' => 'Jetz Sweet Stick Chocolate 65gr',
                'id_jenis_barang' => 1,
                'harga' => 5000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR076',
                'nama' => 'Cheetos jagung bakar 75 gr',
                'id_jenis_barang' => 1,
                'harga' => 5500,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR077',
                'nama' => 'Chiki Twist Ayam Panggang 75 Gr',
                'id_jenis_barang' => 1,
                'harga' => 3600,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR078',
                'nama' => 'Doritos Snack 150gr',
                'id_jenis_barang' => 1,
                'harga' => 7000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR079',
                'nama' => 'Good day cappucino 250ml',
                'id_jenis_barang' => 2,
                'harga' => 6600,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR080',
                'nama' => 'Indocafe Latte Gayo Origins (200ml)',
                'id_jenis_barang' => 2,
                'harga' => 6600,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR081',
                'nama' => 'KAPAL API White Coffee Botol 200 ml',
                'id_jenis_barang' => 2,
                'harga' => 5500,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR082',
                'nama' => 'Luwak Kopi Gula Tradisional Botol 220 ml',
                'id_jenis_barang' => 2,
                'harga' => 4500,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR083',
                'nama' => 'Tic Tac Ori [80 Gr]',
                'id_jenis_barang' => 1,
                'harga' => 4500,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR084',
                'nama' => 'Leo Snack Kentang Keripik Kentang Rasa Ayam Original 10 Gr',
                'id_jenis_barang' => 1,
                'harga' => 4000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR085',
                'nama' => 'Attack Easy Liquid Romantic Flower Botol Detergent [1000 ml]',
                'id_jenis_barang' => 5,
                'harga' => 20000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR086',
                'nama' => 'ATTACK Jaz 1 Pesona Segar Deterjen [900 g]',
                'id_jenis_barang' => 5,
                'harga' => 18000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR087',
                'nama' => 'Attack Plus Softener 450 gr',
                'id_jenis_barang' => 5,
                'harga' => 15000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR088',
                'nama' => 'Attack Softener 800 gr',
                'id_jenis_barang' => 5,
                'harga' => 18000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR089',
                'nama' => 'DAIA Deterjen Bubuk Soft Pink [800 g]',
                'id_jenis_barang' => 5,
                'harga' => 14500,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR090',
                'nama' => 'Rinso Bubuk 800 gr',
                'id_jenis_barang' => 5,
                'harga' => 10000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR091',
                'nama' => 'Rinso Matic Professional Deterjen Laundry Cair 1.65 L',
                'id_jenis_barang' => 5,
                'harga' => 20000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR092',
                'nama' => 'SO KLIN Softergent Pink Cotton Deterjen [800 g]',
                'id_jenis_barang' => 5,
                'harga' => 18000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR093',
                'nama' => 'Harpic 200 ml',
                'id_jenis_barang' => 6,
                'harga' => 10000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR094',
                'nama' => 'So Klin Lemon Pembersih Lantai [800 ml]',
                'id_jenis_barang' => 6,
                'harga' => 7500,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR095',
                'nama' => 'Super Pell Lemon Ginger 400 ml',
                'id_jenis_barang' => 6,
                'harga' => 7000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR096',
                'nama' => 'Super Pell Apple 400 ml',
                'id_jenis_barang' => 6,
                'harga' => 7000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR097',
                'nama' => 'Vixal Pembersih Perselen [500 ml]',
                'id_jenis_barang' => 6,
                'harga' => 10000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR098',
                'nama' => 'Vixal Botol 800 ml',
                'id_jenis_barang' => 6,
                'harga' => 16600,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR099',
                'nama' => 'Wipol Ref 450 ml',
                'id_jenis_barang' => 6,
                'harga' => 6600,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR100',
                'nama' => 'Karbol Wipol Lemon 780 Ml',
                'id_jenis_barang' => 6,
                'harga' => 10000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR101',
                'nama' => 'Cap Kaki Tiga Orange 320 Ml',
                'id_jenis_barang' => 2,
                'harga' => 5600,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR102',
                'nama' => 'Cap Kaki Tiga Guava 320 Ml',
                'id_jenis_barang' => 2,
                'harga' => 5600,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR103',
                'nama' => 'Cap Kaki Tiga Srawbery 320 Ml',
                'id_jenis_barang' => 2,
                'harga' => 5600,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR104',
                'nama' => 'Cap Kaki Tiga Lychee 320 Ml',
                'id_jenis_barang' => 2,
                'harga' => 5600,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR105',
                'nama' => 'Cap Kaki Tiga Guava 320 Ml',
                'id_jenis_barang' => 2,
                'harga' => 5600,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR106',
                'nama' => 'Cap Kaki Tiga Original 200 Ml',
                'id_jenis_barang' => 2,
                'harga' => 3500,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR107',
                'nama' => 'Good Time Double Choco 72gr',
                'id_jenis_barang' => 1,
                'harga' => 3000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR108',
                'nama' => 'Good Time Rainbow Choco 72gr ',
                'id_jenis_barang' => 1,
                'harga' => 3000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR109',
                'nama' => 'Marie Susu 180 Gr',
                'id_jenis_barang' => 1,
                'harga' => 3000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR110',
                'nama' => 'Golda Dolce Latte BTL 200 ml',
                'id_jenis_barang' => 2,
                'harga' => 6000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR111',
                'nama' => 'Potabee Reguler Grilled Seawed 68 Gr',
                'id_jenis_barang' => 1,
                'harga' => 4000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR112',
                'nama' => 'Floridina Orange BTL 350 ml ',
                'id_jenis_barang' => 2,
                'harga' => 3000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR113',
                'nama' => 'Milku Stroberry 200 ml',
                'id_jenis_barang' => 2,
                'harga' => 3000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR114',
                'nama' => 'Japota Ayam Bawang 68 Gr',
                'id_jenis_barang' => 1,
                'harga' => 8000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
            [
                'kode' => 'PR115',
                'nama' => 'Teh Rio Manis Cup 180 ml',
                'id_jenis_barang' => 2,
                'harga' => 1000,
                'id_satuan_barang' => 1,
                'id_supplier' => 1,
            ],
        ]);
    }
}