<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class TransaksiKeluarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \App\Models\TransaksiKeluar::factory()->createMany([
            [
                'barang_id' => 41,
                'jumlah' => 10,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 42,
                'jumlah' => 12,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 43,
                'jumlah' => 12,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 44,
                'jumlah' => 12,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 45,
                'jumlah' => 12,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 28,
                'jumlah' => 6,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 29,
                'jumlah' => 12,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 30,
                'jumlah' => 8,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 31,
                'jumlah' => 8,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 32,
                'jumlah' => 8,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 33,
                'jumlah' => 8,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 34,
                'jumlah' => 8,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 101,
                'jumlah' => 10,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 102,
                'jumlah' => 8,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 103,
                'jumlah' => 9,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 104,
                'jumlah' => 4,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 105,
                'jumlah' => 4,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 106,
                'jumlah' => 4,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 69,
                'jumlah' => 4,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 70,
                'jumlah' => 4,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 71,
                'jumlah' => 16,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 72,
                'jumlah' => 16,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 60,
                'jumlah' => 16,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 61,
                'jumlah' => 16,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 62,
                'jumlah' => 16,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 63,
                'jumlah' => 16,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 64,
                'jumlah' => 12,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 1,
                'jumlah' => 12,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 2,
                'jumlah' => 12,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 3,
                'jumlah' => 12,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 4,
                'jumlah' => 9,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 19,
                'jumlah' => 9,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 20,
                'jumlah' => 9,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 21,
                'jumlah' => 9,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 22,
                'jumlah' => 9,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 23,
                'jumlah' => 9,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 15,
                'jumlah' => 9,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 16,
                'jumlah' => 6,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 17,
                'jumlah' => 6,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 18,
                'jumlah' => 6,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 50,
                'jumlah' => 21,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 51,
                'jumlah' => 21,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 52,
                'jumlah' => 21,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 53,
                'jumlah' => 21,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 54,
                'jumlah' => 21,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 55,
                'jumlah' => 21,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 56,
                'jumlah' => 21,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 111,
                'jumlah' => 15,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 112,
                'jumlah' => 15,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 113,
                'jumlah' => 15,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 114,
                'jumlah' => 15,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 94,
                'jumlah' => 12,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 95,
                'jumlah' => 12,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 96,
                'jumlah' => 23,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 97,
                'jumlah' => 23,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 98,
                'jumlah' => 23,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 99,
                'jumlah' => 23,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 100,
                'jumlah' => 23,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 83,
                'jumlah' => 9,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 84,
                'jumlah' => 9,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 85,
                'jumlah' => 9,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 86,
                'jumlah' => 9,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 89,
                'jumlah' => 9,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 90,
                'jumlah' => 5,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 91,
                'jumlah' => 5,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 92,
                'jumlah' => 5,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 93,
                'jumlah' => 5,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 94,
                'jumlah' => 5,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 95,
                'jumlah' => 12,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 96,
                'jumlah' => 12,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 8,
                'jumlah' => 12,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 9,
                'jumlah' => 11,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 10,
                'jumlah' => 11,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 11,
                'jumlah' => 11,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 12,
                'jumlah' => 11,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 13,
                'jumlah' => 11,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 14,
                'jumlah' => 18,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 15,
                'jumlah' => 18,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 16,
                'jumlah' => 18,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 17,
                'jumlah' => 18,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 18,
                'jumlah' => 18,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 34,
                'jumlah' => 18,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 35,
                'jumlah' => 17,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 36,
                'jumlah' => 17,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 37,
                'jumlah' => 17,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 38,
                'jumlah' => 17,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 39,
                'jumlah' => 17,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 40,
                'jumlah' => 9,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 41,
                'jumlah' => 9,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 42,
                'jumlah' => 9,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 43,
                'jumlah' => 9,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 44,
                'jumlah' => 9,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 45,
                'jumlah' => 10,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 46,
                'jumlah' => 10,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 47,
                'jumlah' => 10,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 48,
                'jumlah' => 10,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 74,
                'jumlah' => 10,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 75,
                'jumlah' => 10,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 76,
                'jumlah' => 19,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 77,
                'jumlah' => 19,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 78,
                'jumlah' => 19,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 79,
                'jumlah' => 19,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 80,
                'jumlah' => 19,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 81,
                'jumlah' => 19,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 110,
                'jumlah' => 19,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 111,
                'jumlah' => 21,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 112,
                'jumlah' => 21,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 113,
                'jumlah' => 21,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 114,
                'jumlah' => 21,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 115,
                'jumlah' => 21,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 106,
                'jumlah' => 21,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 107,
                'jumlah' => 21,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 108,
                'jumlah' => 21,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 109,
                'jumlah' => 21,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 35,
                'jumlah' => 21,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 36,
                'jumlah' => 30,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 37,
                'jumlah' => 10,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 38,
                'jumlah' => 30,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 39,
                'jumlah' => 11,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
            [
                'barang_id' => 40,
                'jumlah' => 12,
                'tanggal_keluar' => '2022-01-01',
                'tanggal_expired' => '2022-01-01',
            ],
        ]);
    }
}